// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sqs

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/sqs"
	mock "github.com/stretchr/testify/mock"
)

// newMocksqsAPI creates a new instance of mocksqsAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMocksqsAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *mocksqsAPI {
	mock := &mocksqsAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mocksqsAPI is an autogenerated mock type for the sqsAPI type
type mocksqsAPI struct {
	mock.Mock
}

type mocksqsAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *mocksqsAPI) EXPECT() *mocksqsAPI_Expecter {
	return &mocksqsAPI_Expecter{mock: &_m.Mock}
}

// DeleteMessage provides a mock function for the type mocksqsAPI
func (_mock *mocksqsAPI) DeleteMessage(ctx context.Context, in *sqs.DeleteMessageInput, opts ...func(*sqs.Options)) (*sqs.DeleteMessageOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteMessage")
	}

	var r0 *sqs.DeleteMessageOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqs.DeleteMessageInput, ...func(*sqs.Options)) (*sqs.DeleteMessageOutput, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqs.DeleteMessageInput, ...func(*sqs.Options)) *sqs.DeleteMessageOutput); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqs.DeleteMessageOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sqs.DeleteMessageInput, ...func(*sqs.Options)) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mocksqsAPI_DeleteMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMessage'
type mocksqsAPI_DeleteMessage_Call struct {
	*mock.Call
}

// DeleteMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - in *sqs.DeleteMessageInput
//   - opts ...func(*sqs.Options)
func (_e *mocksqsAPI_Expecter) DeleteMessage(ctx interface{}, in interface{}, opts ...interface{}) *mocksqsAPI_DeleteMessage_Call {
	return &mocksqsAPI_DeleteMessage_Call{Call: _e.mock.On("DeleteMessage",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *mocksqsAPI_DeleteMessage_Call) Run(run func(ctx context.Context, in *sqs.DeleteMessageInput, opts ...func(*sqs.Options))) *mocksqsAPI_DeleteMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sqs.DeleteMessageInput
		if args[1] != nil {
			arg1 = args[1].(*sqs.DeleteMessageInput)
		}
		var arg2 []func(*sqs.Options)
		var variadicArgs []func(*sqs.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*sqs.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *mocksqsAPI_DeleteMessage_Call) Return(deleteMessageOutput *sqs.DeleteMessageOutput, err error) *mocksqsAPI_DeleteMessage_Call {
	_c.Call.Return(deleteMessageOutput, err)
	return _c
}

func (_c *mocksqsAPI_DeleteMessage_Call) RunAndReturn(run func(ctx context.Context, in *sqs.DeleteMessageInput, opts ...func(*sqs.Options)) (*sqs.DeleteMessageOutput, error)) *mocksqsAPI_DeleteMessage_Call {
	_c.Call.Return(run)
	return _c
}

// ReceiveMessage provides a mock function for the type mocksqsAPI
func (_mock *mocksqsAPI) ReceiveMessage(ctx context.Context, in *sqs.ReceiveMessageInput, opts ...func(*sqs.Options)) (*sqs.ReceiveMessageOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ReceiveMessage")
	}

	var r0 *sqs.ReceiveMessageOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqs.ReceiveMessageInput, ...func(*sqs.Options)) (*sqs.ReceiveMessageOutput, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqs.ReceiveMessageInput, ...func(*sqs.Options)) *sqs.ReceiveMessageOutput); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqs.ReceiveMessageOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sqs.ReceiveMessageInput, ...func(*sqs.Options)) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mocksqsAPI_ReceiveMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReceiveMessage'
type mocksqsAPI_ReceiveMessage_Call struct {
	*mock.Call
}

// ReceiveMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - in *sqs.ReceiveMessageInput
//   - opts ...func(*sqs.Options)
func (_e *mocksqsAPI_Expecter) ReceiveMessage(ctx interface{}, in interface{}, opts ...interface{}) *mocksqsAPI_ReceiveMessage_Call {
	return &mocksqsAPI_ReceiveMessage_Call{Call: _e.mock.On("ReceiveMessage",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *mocksqsAPI_ReceiveMessage_Call) Run(run func(ctx context.Context, in *sqs.ReceiveMessageInput, opts ...func(*sqs.Options))) *mocksqsAPI_ReceiveMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sqs.ReceiveMessageInput
		if args[1] != nil {
			arg1 = args[1].(*sqs.ReceiveMessageInput)
		}
		var arg2 []func(*sqs.Options)
		var variadicArgs []func(*sqs.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*sqs.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *mocksqsAPI_ReceiveMessage_Call) Return(receiveMessageOutput *sqs.ReceiveMessageOutput, err error) *mocksqsAPI_ReceiveMessage_Call {
	_c.Call.Return(receiveMessageOutput, err)
	return _c
}

func (_c *mocksqsAPI_ReceiveMessage_Call) RunAndReturn(run func(ctx context.Context, in *sqs.ReceiveMessageInput, opts ...func(*sqs.Options)) (*sqs.ReceiveMessageOutput, error)) *mocksqsAPI_ReceiveMessage_Call {
	_c.Call.Return(run)
	return _c
}

// SendMessage provides a mock function for the type mocksqsAPI
func (_mock *mocksqsAPI) SendMessage(ctx context.Context, in *sqs.SendMessageInput, opts ...func(*sqs.Options)) (*sqs.SendMessageOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 *sqs.SendMessageOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqs.SendMessageInput, ...func(*sqs.Options)) (*sqs.SendMessageOutput, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqs.SendMessageInput, ...func(*sqs.Options)) *sqs.SendMessageOutput); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqs.SendMessageOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sqs.SendMessageInput, ...func(*sqs.Options)) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mocksqsAPI_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type mocksqsAPI_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - in *sqs.SendMessageInput
//   - opts ...func(*sqs.Options)
func (_e *mocksqsAPI_Expecter) SendMessage(ctx interface{}, in interface{}, opts ...interface{}) *mocksqsAPI_SendMessage_Call {
	return &mocksqsAPI_SendMessage_Call{Call: _e.mock.On("SendMessage",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *mocksqsAPI_SendMessage_Call) Run(run func(ctx context.Context, in *sqs.SendMessageInput, opts ...func(*sqs.Options))) *mocksqsAPI_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sqs.SendMessageInput
		if args[1] != nil {
			arg1 = args[1].(*sqs.SendMessageInput)
		}
		var arg2 []func(*sqs.Options)
		var variadicArgs []func(*sqs.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*sqs.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *mocksqsAPI_SendMessage_Call) Return(sendMessageOutput *sqs.SendMessageOutput, err error) *mocksqsAPI_SendMessage_Call {
	_c.Call.Return(sendMessageOutput, err)
	return _c
}

func (_c *mocksqsAPI_SendMessage_Call) RunAndReturn(run func(ctx context.Context, in *sqs.SendMessageInput, opts ...func(*sqs.Options)) (*sqs.SendMessageOutput, error)) *mocksqsAPI_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}
