// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package secrets

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/secretsmanager"
	mock "github.com/stretchr/testify/mock"
)

// newMocksecretsAPI creates a new instance of mocksecretsAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMocksecretsAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *mocksecretsAPI {
	mock := &mocksecretsAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mocksecretsAPI is an autogenerated mock type for the secretsAPI type
type mocksecretsAPI struct {
	mock.Mock
}

type mocksecretsAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *mocksecretsAPI) EXPECT() *mocksecretsAPI_Expecter {
	return &mocksecretsAPI_Expecter{mock: &_m.Mock}
}

// CreateSecret provides a mock function for the type mocksecretsAPI
func (_mock *mocksecretsAPI) CreateSecret(ctx context.Context, in *secretsmanager.CreateSecretInput, opts ...func(*secretsmanager.Options)) (*secretsmanager.CreateSecretOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CreateSecret")
	}

	var r0 *secretsmanager.CreateSecretOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *secretsmanager.CreateSecretInput, ...func(*secretsmanager.Options)) (*secretsmanager.CreateSecretOutput, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *secretsmanager.CreateSecretInput, ...func(*secretsmanager.Options)) *secretsmanager.CreateSecretOutput); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*secretsmanager.CreateSecretOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *secretsmanager.CreateSecretInput, ...func(*secretsmanager.Options)) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mocksecretsAPI_CreateSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSecret'
type mocksecretsAPI_CreateSecret_Call struct {
	*mock.Call
}

// CreateSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - in *secretsmanager.CreateSecretInput
//   - opts ...func(*secretsmanager.Options)
func (_e *mocksecretsAPI_Expecter) CreateSecret(ctx interface{}, in interface{}, opts ...interface{}) *mocksecretsAPI_CreateSecret_Call {
	return &mocksecretsAPI_CreateSecret_Call{Call: _e.mock.On("CreateSecret",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *mocksecretsAPI_CreateSecret_Call) Run(run func(ctx context.Context, in *secretsmanager.CreateSecretInput, opts ...func(*secretsmanager.Options))) *mocksecretsAPI_CreateSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *secretsmanager.CreateSecretInput
		if args[1] != nil {
			arg1 = args[1].(*secretsmanager.CreateSecretInput)
		}
		var arg2 []func(*secretsmanager.Options)
		var variadicArgs []func(*secretsmanager.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*secretsmanager.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *mocksecretsAPI_CreateSecret_Call) Return(createSecretOutput *secretsmanager.CreateSecretOutput, err error) *mocksecretsAPI_CreateSecret_Call {
	_c.Call.Return(createSecretOutput, err)
	return _c
}

func (_c *mocksecretsAPI_CreateSecret_Call) RunAndReturn(run func(ctx context.Context, in *secretsmanager.CreateSecretInput, opts ...func(*secretsmanager.Options)) (*secretsmanager.CreateSecretOutput, error)) *mocksecretsAPI_CreateSecret_Call {
	_c.Call.Return(run)
	return _c
}

// GetSecretValue provides a mock function for the type mocksecretsAPI
func (_mock *mocksecretsAPI) GetSecretValue(ctx context.Context, in *secretsmanager.GetSecretValueInput, opts ...func(*secretsmanager.Options)) (*secretsmanager.GetSecretValueOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetSecretValue")
	}

	var r0 *secretsmanager.GetSecretValueOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *secretsmanager.GetSecretValueInput, ...func(*secretsmanager.Options)) (*secretsmanager.GetSecretValueOutput, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *secretsmanager.GetSecretValueInput, ...func(*secretsmanager.Options)) *secretsmanager.GetSecretValueOutput); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*secretsmanager.GetSecretValueOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *secretsmanager.GetSecretValueInput, ...func(*secretsmanager.Options)) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mocksecretsAPI_GetSecretValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecretValue'
type mocksecretsAPI_GetSecretValue_Call struct {
	*mock.Call
}

// GetSecretValue is a helper method to define mock.On call
//   - ctx context.Context
//   - in *secretsmanager.GetSecretValueInput
//   - opts ...func(*secretsmanager.Options)
func (_e *mocksecretsAPI_Expecter) GetSecretValue(ctx interface{}, in interface{}, opts ...interface{}) *mocksecretsAPI_GetSecretValue_Call {
	return &mocksecretsAPI_GetSecretValue_Call{Call: _e.mock.On("GetSecretValue",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *mocksecretsAPI_GetSecretValue_Call) Run(run func(ctx context.Context, in *secretsmanager.GetSecretValueInput, opts ...func(*secretsmanager.Options))) *mocksecretsAPI_GetSecretValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *secretsmanager.GetSecretValueInput
		if args[1] != nil {
			arg1 = args[1].(*secretsmanager.GetSecretValueInput)
		}
		var arg2 []func(*secretsmanager.Options)
		var variadicArgs []func(*secretsmanager.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*secretsmanager.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *mocksecretsAPI_GetSecretValue_Call) Return(getSecretValueOutput *secretsmanager.GetSecretValueOutput, err error) *mocksecretsAPI_GetSecretValue_Call {
	_c.Call.Return(getSecretValueOutput, err)
	return _c
}

func (_c *mocksecretsAPI_GetSecretValue_Call) RunAndReturn(run func(ctx context.Context, in *secretsmanager.GetSecretValueInput, opts ...func(*secretsmanager.Options)) (*secretsmanager.GetSecretValueOutput, error)) *mocksecretsAPI_GetSecretValue_Call {
	_c.Call.Return(run)
	return _c
}

// PutSecretValue provides a mock function for the type mocksecretsAPI
func (_mock *mocksecretsAPI) PutSecretValue(ctx context.Context, in *secretsmanager.PutSecretValueInput, opts ...func(*secretsmanager.Options)) (*secretsmanager.PutSecretValueOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PutSecretValue")
	}

	var r0 *secretsmanager.PutSecretValueOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *secretsmanager.PutSecretValueInput, ...func(*secretsmanager.Options)) (*secretsmanager.PutSecretValueOutput, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *secretsmanager.PutSecretValueInput, ...func(*secretsmanager.Options)) *secretsmanager.PutSecretValueOutput); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*secretsmanager.PutSecretValueOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *secretsmanager.PutSecretValueInput, ...func(*secretsmanager.Options)) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mocksecretsAPI_PutSecretValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutSecretValue'
type mocksecretsAPI_PutSecretValue_Call struct {
	*mock.Call
}

// PutSecretValue is a helper method to define mock.On call
//   - ctx context.Context
//   - in *secretsmanager.PutSecretValueInput
//   - opts ...func(*secretsmanager.Options)
func (_e *mocksecretsAPI_Expecter) PutSecretValue(ctx interface{}, in interface{}, opts ...interface{}) *mocksecretsAPI_PutSecretValue_Call {
	return &mocksecretsAPI_PutSecretValue_Call{Call: _e.mock.On("PutSecretValue",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *mocksecretsAPI_PutSecretValue_Call) Run(run func(ctx context.Context, in *secretsmanager.PutSecretValueInput, opts ...func(*secretsmanager.Options))) *mocksecretsAPI_PutSecretValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *secretsmanager.PutSecretValueInput
		if args[1] != nil {
			arg1 = args[1].(*secretsmanager.PutSecretValueInput)
		}
		var arg2 []func(*secretsmanager.Options)
		var variadicArgs []func(*secretsmanager.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*secretsmanager.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *mocksecretsAPI_PutSecretValue_Call) Return(putSecretValueOutput *secretsmanager.PutSecretValueOutput, err error) *mocksecretsAPI_PutSecretValue_Call {
	_c.Call.Return(putSecretValueOutput, err)
	return _c
}

func (_c *mocksecretsAPI_PutSecretValue_Call) RunAndReturn(run func(ctx context.Context, in *secretsmanager.PutSecretValueInput, opts ...func(*secretsmanager.Options)) (*secretsmanager.PutSecretValueOutput, error)) *mocksecretsAPI_PutSecretValue_Call {
	_c.Call.Return(run)
	return _c
}
