// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package tasks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// Cancel provides a mock function for the type MockStore
func (_mock *MockStore) Cancel(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type MockStore_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockStore_Expecter) Cancel(ctx interface{}, id interface{}) *MockStore_Cancel_Call {
	return &MockStore_Cancel_Call{Call: _e.mock.On("Cancel", ctx, id)}
}

func (_c *MockStore_Cancel_Call) Run(run func(ctx context.Context, id string)) *MockStore_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_Cancel_Call) Return(err error) *MockStore_Cancel_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_Cancel_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockStore_Cancel_Call {
	_c.Call.Return(run)
	return _c
}

// Claim provides a mock function for the type MockStore
func (_mock *MockStore) Claim(ctx context.Context, queue string, workerID string, visibility time.Duration) (*Record, error) {
	ret := _mock.Called(ctx, queue, workerID, visibility)

	if len(ret) == 0 {
		panic("no return value specified for Claim")
	}

	var r0 *Record
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) (*Record, error)); ok {
		return returnFunc(ctx, queue, workerID, visibility)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) *Record); ok {
		r0 = returnFunc(ctx, queue, workerID, visibility)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Record)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, time.Duration) error); ok {
		r1 = returnFunc(ctx, queue, workerID, visibility)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_Claim_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Claim'
type MockStore_Claim_Call struct {
	*mock.Call
}

// Claim is a helper method to define mock.On call
//   - ctx context.Context
//   - queue string
//   - workerID string
//   - visibility time.Duration
func (_e *MockStore_Expecter) Claim(ctx interface{}, queue interface{}, workerID interface{}, visibility interface{}) *MockStore_Claim_Call {
	return &MockStore_Claim_Call{Call: _e.mock.On("Claim", ctx, queue, workerID, visibility)}
}

func (_c *MockStore_Claim_Call) Run(run func(ctx context.Context, queue string, workerID string, visibility time.Duration)) *MockStore_Claim_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStore_Claim_Call) Return(record *Record, err error) *MockStore_Claim_Call {
	_c.Call.Return(record, err)
	return _c
}

func (_c *MockStore_Claim_Call) RunAndReturn(run func(ctx context.Context, queue string, workerID string, visibility time.Duration) (*Record, error)) *MockStore_Claim_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockStore
func (_mock *MockStore) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockStore_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockStore_Expecter) Close() *MockStore_Close_Call {
	return &MockStore_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockStore_Close_Call) Run(run func()) *MockStore_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStore_Close_Call) Return(err error) *MockStore_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_Close_Call) RunAndReturn(run func() error) *MockStore_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Complete provides a mock function for the type MockStore
func (_mock *MockStore) Complete(ctx context.Context, id string, workerID string) error {
	ret := _mock.Called(ctx, id, workerID)

	if len(ret) == 0 {
		panic("no return value specified for Complete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, id, workerID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_Complete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Complete'
type MockStore_Complete_Call struct {
	*mock.Call
}

// Complete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - workerID string
func (_e *MockStore_Expecter) Complete(ctx interface{}, id interface{}, workerID interface{}) *MockStore_Complete_Call {
	return &MockStore_Complete_Call{Call: _e.mock.On("Complete", ctx, id, workerID)}
}

func (_c *MockStore_Complete_Call) Run(run func(ctx context.Context, id string, workerID string)) *MockStore_Complete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_Complete_Call) Return(err error) *MockStore_Complete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_Complete_Call) RunAndReturn(run func(ctx context.Context, id string, workerID string) error) *MockStore_Complete_Call {
	_c.Call.Return(run)
	return _c
}

// Enqueue provides a mock function for the type MockStore
func (_mock *MockStore) Enqueue(ctx context.Context, t Task) (Record, error) {
	ret := _mock.Called(ctx, t)

	if len(ret) == 0 {
		panic("no return value specified for Enqueue")
	}

	var r0 Record
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Task) (Record, error)); ok {
		return returnFunc(ctx, t)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, Task) Record); ok {
		r0 = returnFunc(ctx, t)
	} else {
		r0 = ret.Get(0).(Record)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, Task) error); ok {
		r1 = returnFunc(ctx, t)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_Enqueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enqueue'
type MockStore_Enqueue_Call struct {
	*mock.Call
}

// Enqueue is a helper method to define mock.On call
//   - ctx context.Context
//   - t Task
func (_e *MockStore_Expecter) Enqueue(ctx interface{}, t interface{}) *MockStore_Enqueue_Call {
	return &MockStore_Enqueue_Call{Call: _e.mock.On("Enqueue", ctx, t)}
}

func (_c *MockStore_Enqueue_Call) Run(run func(ctx context.Context, t Task)) *MockStore_Enqueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Task
		if args[1] != nil {
			arg1 = args[1].(Task)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_Enqueue_Call) Return(record Record, err error) *MockStore_Enqueue_Call {
	_c.Call.Return(record, err)
	return _c
}

func (_c *MockStore_Enqueue_Call) RunAndReturn(run func(ctx context.Context, t Task) (Record, error)) *MockStore_Enqueue_Call {
	_c.Call.Return(run)
	return _c
}

// Fail provides a mock function for the type MockStore
func (_mock *MockStore) Fail(ctx context.Context, id string, workerID string, errMsg string, nextAttemptAt *time.Time) error {
	ret := _mock.Called(ctx, id, workerID, errMsg, nextAttemptAt)

	if len(ret) == 0 {
		panic("no return value specified for Fail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, *time.Time) error); ok {
		r0 = returnFunc(ctx, id, workerID, errMsg, nextAttemptAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_Fail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fail'
type MockStore_Fail_Call struct {
	*mock.Call
}

// Fail is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - workerID string
//   - errMsg string
//   - nextAttemptAt *time.Time
func (_e *MockStore_Expecter) Fail(ctx interface{}, id interface{}, workerID interface{}, errMsg interface{}, nextAttemptAt interface{}) *MockStore_Fail_Call {
	return &MockStore_Fail_Call{Call: _e.mock.On("Fail", ctx, id, workerID, errMsg, nextAttemptAt)}
}

func (_c *MockStore_Fail_Call) Run(run func(ctx context.Context, id string, workerID string, errMsg string, nextAttemptAt *time.Time)) *MockStore_Fail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 *time.Time
		if args[4] != nil {
			arg4 = args[4].(*time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockStore_Fail_Call) Return(err error) *MockStore_Fail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_Fail_Call) RunAndReturn(run func(ctx context.Context, id string, workerID string, errMsg string, nextAttemptAt *time.Time) error) *MockStore_Fail_Call {
	_c.Call.Return(run)
	return _c
}

// Heartbeat provides a mock function for the type MockStore
func (_mock *MockStore) Heartbeat(ctx context.Context, id string, workerID string, extend time.Duration) error {
	ret := _mock.Called(ctx, id, workerID, extend)

	if len(ret) == 0 {
		panic("no return value specified for Heartbeat")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) error); ok {
		r0 = returnFunc(ctx, id, workerID, extend)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_Heartbeat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Heartbeat'
type MockStore_Heartbeat_Call struct {
	*mock.Call
}

// Heartbeat is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - workerID string
//   - extend time.Duration
func (_e *MockStore_Expecter) Heartbeat(ctx interface{}, id interface{}, workerID interface{}, extend interface{}) *MockStore_Heartbeat_Call {
	return &MockStore_Heartbeat_Call{Call: _e.mock.On("Heartbeat", ctx, id, workerID, extend)}
}

func (_c *MockStore_Heartbeat_Call) Run(run func(ctx context.Context, id string, workerID string, extend time.Duration)) *MockStore_Heartbeat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStore_Heartbeat_Call) Return(err error) *MockStore_Heartbeat_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_Heartbeat_Call) RunAndReturn(run func(ctx context.Context, id string, workerID string, extend time.Duration) error) *MockStore_Heartbeat_Call {
	_c.Call.Return(run)
	return _c
}

// Inspect provides a mock function for the type MockStore
func (_mock *MockStore) Inspect(ctx context.Context, id string) (Record, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Inspect")
	}

	var r0 Record
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (Record, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) Record); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(Record)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_Inspect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Inspect'
type MockStore_Inspect_Call struct {
	*mock.Call
}

// Inspect is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockStore_Expecter) Inspect(ctx interface{}, id interface{}) *MockStore_Inspect_Call {
	return &MockStore_Inspect_Call{Call: _e.mock.On("Inspect", ctx, id)}
}

func (_c *MockStore_Inspect_Call) Run(run func(ctx context.Context, id string)) *MockStore_Inspect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_Inspect_Call) Return(record Record, err error) *MockStore_Inspect_Call {
	_c.Call.Return(record, err)
	return _c
}

func (_c *MockStore_Inspect_Call) RunAndReturn(run func(ctx context.Context, id string) (Record, error)) *MockStore_Inspect_Call {
	_c.Call.Return(run)
	return _c
}

// PromoteScheduled provides a mock function for the type MockStore
func (_mock *MockStore) PromoteScheduled(ctx context.Context, queue string, now time.Time) (int, error) {
	ret := _mock.Called(ctx, queue, now)

	if len(ret) == 0 {
		panic("no return value specified for PromoteScheduled")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) (int, error)); ok {
		return returnFunc(ctx, queue, now)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) int); ok {
		r0 = returnFunc(ctx, queue, now)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = returnFunc(ctx, queue, now)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_PromoteScheduled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PromoteScheduled'
type MockStore_PromoteScheduled_Call struct {
	*mock.Call
}

// PromoteScheduled is a helper method to define mock.On call
//   - ctx context.Context
//   - queue string
//   - now time.Time
func (_e *MockStore_Expecter) PromoteScheduled(ctx interface{}, queue interface{}, now interface{}) *MockStore_PromoteScheduled_Call {
	return &MockStore_PromoteScheduled_Call{Call: _e.mock.On("PromoteScheduled", ctx, queue, now)}
}

func (_c *MockStore_PromoteScheduled_Call) Run(run func(ctx context.Context, queue string, now time.Time)) *MockStore_PromoteScheduled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_PromoteScheduled_Call) Return(n int, err error) *MockStore_PromoteScheduled_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockStore_PromoteScheduled_Call) RunAndReturn(run func(ctx context.Context, queue string, now time.Time) (int, error)) *MockStore_PromoteScheduled_Call {
	_c.Call.Return(run)
	return _c
}

// PurgeOlderThan provides a mock function for the type MockStore
func (_mock *MockStore) PurgeOlderThan(ctx context.Context, cutoff time.Time) (int, error) {
	ret := _mock.Called(ctx, cutoff)

	if len(ret) == 0 {
		panic("no return value specified for PurgeOlderThan")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) (int, error)); ok {
		return returnFunc(ctx, cutoff)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) int); ok {
		r0 = returnFunc(ctx, cutoff)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = returnFunc(ctx, cutoff)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_PurgeOlderThan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PurgeOlderThan'
type MockStore_PurgeOlderThan_Call struct {
	*mock.Call
}

// PurgeOlderThan is a helper method to define mock.On call
//   - ctx context.Context
//   - cutoff time.Time
func (_e *MockStore_Expecter) PurgeOlderThan(ctx interface{}, cutoff interface{}) *MockStore_PurgeOlderThan_Call {
	return &MockStore_PurgeOlderThan_Call{Call: _e.mock.On("PurgeOlderThan", ctx, cutoff)}
}

func (_c *MockStore_PurgeOlderThan_Call) Run(run func(ctx context.Context, cutoff time.Time)) *MockStore_PurgeOlderThan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_PurgeOlderThan_Call) Return(n int, err error) *MockStore_PurgeOlderThan_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockStore_PurgeOlderThan_Call) RunAndReturn(run func(ctx context.Context, cutoff time.Time) (int, error)) *MockStore_PurgeOlderThan_Call {
	_c.Call.Return(run)
	return _c
}

// QueueStats provides a mock function for the type MockStore
func (_mock *MockStore) QueueStats(ctx context.Context, queue string) (QueueStats, error) {
	ret := _mock.Called(ctx, queue)

	if len(ret) == 0 {
		panic("no return value specified for QueueStats")
	}

	var r0 QueueStats
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (QueueStats, error)); ok {
		return returnFunc(ctx, queue)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) QueueStats); ok {
		r0 = returnFunc(ctx, queue)
	} else {
		r0 = ret.Get(0).(QueueStats)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, queue)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_QueueStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueueStats'
type MockStore_QueueStats_Call struct {
	*mock.Call
}

// QueueStats is a helper method to define mock.On call
//   - ctx context.Context
//   - queue string
func (_e *MockStore_Expecter) QueueStats(ctx interface{}, queue interface{}) *MockStore_QueueStats_Call {
	return &MockStore_QueueStats_Call{Call: _e.mock.On("QueueStats", ctx, queue)}
}

func (_c *MockStore_QueueStats_Call) Run(run func(ctx context.Context, queue string)) *MockStore_QueueStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_QueueStats_Call) Return(queueStats QueueStats, err error) *MockStore_QueueStats_Call {
	_c.Call.Return(queueStats, err)
	return _c
}

func (_c *MockStore_QueueStats_Call) RunAndReturn(run func(ctx context.Context, queue string) (QueueStats, error)) *MockStore_QueueStats_Call {
	_c.Call.Return(run)
	return _c
}

// ReclaimExpired provides a mock function for the type MockStore
func (_mock *MockStore) ReclaimExpired(ctx context.Context, queue string, now time.Time) (int, error) {
	ret := _mock.Called(ctx, queue, now)

	if len(ret) == 0 {
		panic("no return value specified for ReclaimExpired")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) (int, error)); ok {
		return returnFunc(ctx, queue, now)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) int); ok {
		r0 = returnFunc(ctx, queue, now)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = returnFunc(ctx, queue, now)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_ReclaimExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReclaimExpired'
type MockStore_ReclaimExpired_Call struct {
	*mock.Call
}

// ReclaimExpired is a helper method to define mock.On call
//   - ctx context.Context
//   - queue string
//   - now time.Time
func (_e *MockStore_Expecter) ReclaimExpired(ctx interface{}, queue interface{}, now interface{}) *MockStore_ReclaimExpired_Call {
	return &MockStore_ReclaimExpired_Call{Call: _e.mock.On("ReclaimExpired", ctx, queue, now)}
}

func (_c *MockStore_ReclaimExpired_Call) Run(run func(ctx context.Context, queue string, now time.Time)) *MockStore_ReclaimExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_ReclaimExpired_Call) Return(n int, err error) *MockStore_ReclaimExpired_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockStore_ReclaimExpired_Call) RunAndReturn(run func(ctx context.Context, queue string, now time.Time) (int, error)) *MockStore_ReclaimExpired_Call {
	_c.Call.Return(run)
	return _c
}

// ScheduleAt provides a mock function for the type MockStore
func (_mock *MockStore) ScheduleAt(ctx context.Context, when time.Time, t Task) (Record, error) {
	ret := _mock.Called(ctx, when, t)

	if len(ret) == 0 {
		panic("no return value specified for ScheduleAt")
	}

	var r0 Record
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, Task) (Record, error)); ok {
		return returnFunc(ctx, when, t)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, Task) Record); ok {
		r0 = returnFunc(ctx, when, t)
	} else {
		r0 = ret.Get(0).(Record)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time, Task) error); ok {
		r1 = returnFunc(ctx, when, t)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_ScheduleAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScheduleAt'
type MockStore_ScheduleAt_Call struct {
	*mock.Call
}

// ScheduleAt is a helper method to define mock.On call
//   - ctx context.Context
//   - when time.Time
//   - t Task
func (_e *MockStore_Expecter) ScheduleAt(ctx interface{}, when interface{}, t interface{}) *MockStore_ScheduleAt_Call {
	return &MockStore_ScheduleAt_Call{Call: _e.mock.On("ScheduleAt", ctx, when, t)}
}

func (_c *MockStore_ScheduleAt_Call) Run(run func(ctx context.Context, when time.Time, t Task)) *MockStore_ScheduleAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 Task
		if args[2] != nil {
			arg2 = args[2].(Task)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_ScheduleAt_Call) Return(record Record, err error) *MockStore_ScheduleAt_Call {
	_c.Call.Return(record, err)
	return _c
}

func (_c *MockStore_ScheduleAt_Call) RunAndReturn(run func(ctx context.Context, when time.Time, t Task) (Record, error)) *MockStore_ScheduleAt_Call {
	_c.Call.Return(run)
	return _c
}
