// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package docker

import (
	"context"
	"io"

	"github.com/docker/docker/api/types/build"
	"github.com/docker/docker/api/types/container"
	"github.com/docker/docker/api/types/image"
	"github.com/docker/docker/api/types/network"
	"github.com/opencontainers/image-spec/specs-go/v1"
	mock "github.com/stretchr/testify/mock"
)

// newMockdockerAPI creates a new instance of mockdockerAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockdockerAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockdockerAPI {
	mock := &mockdockerAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockdockerAPI is an autogenerated mock type for the dockerAPI type
type mockdockerAPI struct {
	mock.Mock
}

type mockdockerAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *mockdockerAPI) EXPECT() *mockdockerAPI_Expecter {
	return &mockdockerAPI_Expecter{mock: &_m.Mock}
}

// BuildCancel provides a mock function for the type mockdockerAPI
func (_mock *mockdockerAPI) BuildCancel(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for BuildCancel")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockdockerAPI_BuildCancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildCancel'
type mockdockerAPI_BuildCancel_Call struct {
	*mock.Call
}

// BuildCancel is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *mockdockerAPI_Expecter) BuildCancel(ctx interface{}, id interface{}) *mockdockerAPI_BuildCancel_Call {
	return &mockdockerAPI_BuildCancel_Call{Call: _e.mock.On("BuildCancel", ctx, id)}
}

func (_c *mockdockerAPI_BuildCancel_Call) Run(run func(ctx context.Context, id string)) *mockdockerAPI_BuildCancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockdockerAPI_BuildCancel_Call) Return(err error) *mockdockerAPI_BuildCancel_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockdockerAPI_BuildCancel_Call) RunAndReturn(run func(ctx context.Context, id string) error) *mockdockerAPI_BuildCancel_Call {
	_c.Call.Return(run)
	return _c
}

// ContainerCreate provides a mock function for the type mockdockerAPI
func (_mock *mockdockerAPI) ContainerCreate(ctx context.Context, config *container.Config, hostConfig *container.HostConfig, networkingConfig *network.NetworkingConfig, platform *v1.Platform, containerName string) (container.CreateResponse, error) {
	ret := _mock.Called(ctx, config, hostConfig, networkingConfig, platform, containerName)

	if len(ret) == 0 {
		panic("no return value specified for ContainerCreate")
	}

	var r0 container.CreateResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *container.Config, *container.HostConfig, *network.NetworkingConfig, *v1.Platform, string) (container.CreateResponse, error)); ok {
		return returnFunc(ctx, config, hostConfig, networkingConfig, platform, containerName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *container.Config, *container.HostConfig, *network.NetworkingConfig, *v1.Platform, string) container.CreateResponse); ok {
		r0 = returnFunc(ctx, config, hostConfig, networkingConfig, platform, containerName)
	} else {
		r0 = ret.Get(0).(container.CreateResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *container.Config, *container.HostConfig, *network.NetworkingConfig, *v1.Platform, string) error); ok {
		r1 = returnFunc(ctx, config, hostConfig, networkingConfig, platform, containerName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockdockerAPI_ContainerCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerCreate'
type mockdockerAPI_ContainerCreate_Call struct {
	*mock.Call
}

// ContainerCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - config *container.Config
//   - hostConfig *container.HostConfig
//   - networkingConfig *network.NetworkingConfig
//   - platform *v1.Platform
//   - containerName string
func (_e *mockdockerAPI_Expecter) ContainerCreate(ctx interface{}, config interface{}, hostConfig interface{}, networkingConfig interface{}, platform interface{}, containerName interface{}) *mockdockerAPI_ContainerCreate_Call {
	return &mockdockerAPI_ContainerCreate_Call{Call: _e.mock.On("ContainerCreate", ctx, config, hostConfig, networkingConfig, platform, containerName)}
}

func (_c *mockdockerAPI_ContainerCreate_Call) Run(run func(ctx context.Context, config *container.Config, hostConfig *container.HostConfig, networkingConfig *network.NetworkingConfig, platform *v1.Platform, containerName string)) *mockdockerAPI_ContainerCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *container.Config
		if args[1] != nil {
			arg1 = args[1].(*container.Config)
		}
		var arg2 *container.HostConfig
		if args[2] != nil {
			arg2 = args[2].(*container.HostConfig)
		}
		var arg3 *network.NetworkingConfig
		if args[3] != nil {
			arg3 = args[3].(*network.NetworkingConfig)
		}
		var arg4 *v1.Platform
		if args[4] != nil {
			arg4 = args[4].(*v1.Platform)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *mockdockerAPI_ContainerCreate_Call) Return(createResponse container.CreateResponse, err error) *mockdockerAPI_ContainerCreate_Call {
	_c.Call.Return(createResponse, err)
	return _c
}

func (_c *mockdockerAPI_ContainerCreate_Call) RunAndReturn(run func(ctx context.Context, config *container.Config, hostConfig *container.HostConfig, networkingConfig *network.NetworkingConfig, platform *v1.Platform, containerName string) (container.CreateResponse, error)) *mockdockerAPI_ContainerCreate_Call {
	_c.Call.Return(run)
	return _c
}

// ContainerInspect provides a mock function for the type mockdockerAPI
func (_mock *mockdockerAPI) ContainerInspect(ctx context.Context, containerID string) (container.InspectResponse, error) {
	ret := _mock.Called(ctx, containerID)

	if len(ret) == 0 {
		panic("no return value specified for ContainerInspect")
	}

	var r0 container.InspectResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (container.InspectResponse, error)); ok {
		return returnFunc(ctx, containerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) container.InspectResponse); ok {
		r0 = returnFunc(ctx, containerID)
	} else {
		r0 = ret.Get(0).(container.InspectResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, containerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockdockerAPI_ContainerInspect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerInspect'
type mockdockerAPI_ContainerInspect_Call struct {
	*mock.Call
}

// ContainerInspect is a helper method to define mock.On call
//   - ctx context.Context
//   - containerID string
func (_e *mockdockerAPI_Expecter) ContainerInspect(ctx interface{}, containerID interface{}) *mockdockerAPI_ContainerInspect_Call {
	return &mockdockerAPI_ContainerInspect_Call{Call: _e.mock.On("ContainerInspect", ctx, containerID)}
}

func (_c *mockdockerAPI_ContainerInspect_Call) Run(run func(ctx context.Context, containerID string)) *mockdockerAPI_ContainerInspect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockdockerAPI_ContainerInspect_Call) Return(inspectResponse container.InspectResponse, err error) *mockdockerAPI_ContainerInspect_Call {
	_c.Call.Return(inspectResponse, err)
	return _c
}

func (_c *mockdockerAPI_ContainerInspect_Call) RunAndReturn(run func(ctx context.Context, containerID string) (container.InspectResponse, error)) *mockdockerAPI_ContainerInspect_Call {
	_c.Call.Return(run)
	return _c
}

// ContainerKill provides a mock function for the type mockdockerAPI
func (_mock *mockdockerAPI) ContainerKill(ctx context.Context, containerID string, signal string) error {
	ret := _mock.Called(ctx, containerID, signal)

	if len(ret) == 0 {
		panic("no return value specified for ContainerKill")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, containerID, signal)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockdockerAPI_ContainerKill_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerKill'
type mockdockerAPI_ContainerKill_Call struct {
	*mock.Call
}

// ContainerKill is a helper method to define mock.On call
//   - ctx context.Context
//   - containerID string
//   - signal string
func (_e *mockdockerAPI_Expecter) ContainerKill(ctx interface{}, containerID interface{}, signal interface{}) *mockdockerAPI_ContainerKill_Call {
	return &mockdockerAPI_ContainerKill_Call{Call: _e.mock.On("ContainerKill", ctx, containerID, signal)}
}

func (_c *mockdockerAPI_ContainerKill_Call) Run(run func(ctx context.Context, containerID string, signal string)) *mockdockerAPI_ContainerKill_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockdockerAPI_ContainerKill_Call) Return(err error) *mockdockerAPI_ContainerKill_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockdockerAPI_ContainerKill_Call) RunAndReturn(run func(ctx context.Context, containerID string, signal string) error) *mockdockerAPI_ContainerKill_Call {
	_c.Call.Return(run)
	return _c
}

// ContainerList provides a mock function for the type mockdockerAPI
func (_mock *mockdockerAPI) ContainerList(ctx context.Context, options container.ListOptions) ([]container.Summary, error) {
	ret := _mock.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for ContainerList")
	}

	var r0 []container.Summary
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, container.ListOptions) ([]container.Summary, error)); ok {
		return returnFunc(ctx, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, container.ListOptions) []container.Summary); ok {
		r0 = returnFunc(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]container.Summary)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, container.ListOptions) error); ok {
		r1 = returnFunc(ctx, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockdockerAPI_ContainerList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerList'
type mockdockerAPI_ContainerList_Call struct {
	*mock.Call
}

// ContainerList is a helper method to define mock.On call
//   - ctx context.Context
//   - options container.ListOptions
func (_e *mockdockerAPI_Expecter) ContainerList(ctx interface{}, options interface{}) *mockdockerAPI_ContainerList_Call {
	return &mockdockerAPI_ContainerList_Call{Call: _e.mock.On("ContainerList", ctx, options)}
}

func (_c *mockdockerAPI_ContainerList_Call) Run(run func(ctx context.Context, options container.ListOptions)) *mockdockerAPI_ContainerList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 container.ListOptions
		if args[1] != nil {
			arg1 = args[1].(container.ListOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockdockerAPI_ContainerList_Call) Return(summarys []container.Summary, err error) *mockdockerAPI_ContainerList_Call {
	_c.Call.Return(summarys, err)
	return _c
}

func (_c *mockdockerAPI_ContainerList_Call) RunAndReturn(run func(ctx context.Context, options container.ListOptions) ([]container.Summary, error)) *mockdockerAPI_ContainerList_Call {
	_c.Call.Return(run)
	return _c
}

// ContainerLogs provides a mock function for the type mockdockerAPI
func (_mock *mockdockerAPI) ContainerLogs(ctx context.Context, containerID string, options container.LogsOptions) (io.ReadCloser, error) {
	ret := _mock.Called(ctx, containerID, options)

	if len(ret) == 0 {
		panic("no return value specified for ContainerLogs")
	}

	var r0 io.ReadCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, container.LogsOptions) (io.ReadCloser, error)); ok {
		return returnFunc(ctx, containerID, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, container.LogsOptions) io.ReadCloser); ok {
		r0 = returnFunc(ctx, containerID, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, container.LogsOptions) error); ok {
		r1 = returnFunc(ctx, containerID, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockdockerAPI_ContainerLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerLogs'
type mockdockerAPI_ContainerLogs_Call struct {
	*mock.Call
}

// ContainerLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - containerID string
//   - options container.LogsOptions
func (_e *mockdockerAPI_Expecter) ContainerLogs(ctx interface{}, containerID interface{}, options interface{}) *mockdockerAPI_ContainerLogs_Call {
	return &mockdockerAPI_ContainerLogs_Call{Call: _e.mock.On("ContainerLogs", ctx, containerID, options)}
}

func (_c *mockdockerAPI_ContainerLogs_Call) Run(run func(ctx context.Context, containerID string, options container.LogsOptions)) *mockdockerAPI_ContainerLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 container.LogsOptions
		if args[2] != nil {
			arg2 = args[2].(container.LogsOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockdockerAPI_ContainerLogs_Call) Return(readCloser io.ReadCloser, err error) *mockdockerAPI_ContainerLogs_Call {
	_c.Call.Return(readCloser, err)
	return _c
}

func (_c *mockdockerAPI_ContainerLogs_Call) RunAndReturn(run func(ctx context.Context, containerID string, options container.LogsOptions) (io.ReadCloser, error)) *mockdockerAPI_ContainerLogs_Call {
	_c.Call.Return(run)
	return _c
}

// ContainerRemove provides a mock function for the type mockdockerAPI
func (_mock *mockdockerAPI) ContainerRemove(ctx context.Context, containerID string, options container.RemoveOptions) error {
	ret := _mock.Called(ctx, containerID, options)

	if len(ret) == 0 {
		panic("no return value specified for ContainerRemove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, container.RemoveOptions) error); ok {
		r0 = returnFunc(ctx, containerID, options)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockdockerAPI_ContainerRemove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerRemove'
type mockdockerAPI_ContainerRemove_Call struct {
	*mock.Call
}

// ContainerRemove is a helper method to define mock.On call
//   - ctx context.Context
//   - containerID string
//   - options container.RemoveOptions
func (_e *mockdockerAPI_Expecter) ContainerRemove(ctx interface{}, containerID interface{}, options interface{}) *mockdockerAPI_ContainerRemove_Call {
	return &mockdockerAPI_ContainerRemove_Call{Call: _e.mock.On("ContainerRemove", ctx, containerID, options)}
}

func (_c *mockdockerAPI_ContainerRemove_Call) Run(run func(ctx context.Context, containerID string, options container.RemoveOptions)) *mockdockerAPI_ContainerRemove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 container.RemoveOptions
		if args[2] != nil {
			arg2 = args[2].(container.RemoveOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockdockerAPI_ContainerRemove_Call) Return(err error) *mockdockerAPI_ContainerRemove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockdockerAPI_ContainerRemove_Call) RunAndReturn(run func(ctx context.Context, containerID string, options container.RemoveOptions) error) *mockdockerAPI_ContainerRemove_Call {
	_c.Call.Return(run)
	return _c
}

// ContainerRestart provides a mock function for the type mockdockerAPI
func (_mock *mockdockerAPI) ContainerRestart(ctx context.Context, containerID string, options container.StopOptions) error {
	ret := _mock.Called(ctx, containerID, options)

	if len(ret) == 0 {
		panic("no return value specified for ContainerRestart")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, container.StopOptions) error); ok {
		r0 = returnFunc(ctx, containerID, options)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockdockerAPI_ContainerRestart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerRestart'
type mockdockerAPI_ContainerRestart_Call struct {
	*mock.Call
}

// ContainerRestart is a helper method to define mock.On call
//   - ctx context.Context
//   - containerID string
//   - options container.StopOptions
func (_e *mockdockerAPI_Expecter) ContainerRestart(ctx interface{}, containerID interface{}, options interface{}) *mockdockerAPI_ContainerRestart_Call {
	return &mockdockerAPI_ContainerRestart_Call{Call: _e.mock.On("ContainerRestart", ctx, containerID, options)}
}

func (_c *mockdockerAPI_ContainerRestart_Call) Run(run func(ctx context.Context, containerID string, options container.StopOptions)) *mockdockerAPI_ContainerRestart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 container.StopOptions
		if args[2] != nil {
			arg2 = args[2].(container.StopOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockdockerAPI_ContainerRestart_Call) Return(err error) *mockdockerAPI_ContainerRestart_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockdockerAPI_ContainerRestart_Call) RunAndReturn(run func(ctx context.Context, containerID string, options container.StopOptions) error) *mockdockerAPI_ContainerRestart_Call {
	_c.Call.Return(run)
	return _c
}

// ContainerStart provides a mock function for the type mockdockerAPI
func (_mock *mockdockerAPI) ContainerStart(ctx context.Context, containerID string, options container.StartOptions) error {
	ret := _mock.Called(ctx, containerID, options)

	if len(ret) == 0 {
		panic("no return value specified for ContainerStart")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, container.StartOptions) error); ok {
		r0 = returnFunc(ctx, containerID, options)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockdockerAPI_ContainerStart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerStart'
type mockdockerAPI_ContainerStart_Call struct {
	*mock.Call
}

// ContainerStart is a helper method to define mock.On call
//   - ctx context.Context
//   - containerID string
//   - options container.StartOptions
func (_e *mockdockerAPI_Expecter) ContainerStart(ctx interface{}, containerID interface{}, options interface{}) *mockdockerAPI_ContainerStart_Call {
	return &mockdockerAPI_ContainerStart_Call{Call: _e.mock.On("ContainerStart", ctx, containerID, options)}
}

func (_c *mockdockerAPI_ContainerStart_Call) Run(run func(ctx context.Context, containerID string, options container.StartOptions)) *mockdockerAPI_ContainerStart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 container.StartOptions
		if args[2] != nil {
			arg2 = args[2].(container.StartOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockdockerAPI_ContainerStart_Call) Return(err error) *mockdockerAPI_ContainerStart_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockdockerAPI_ContainerStart_Call) RunAndReturn(run func(ctx context.Context, containerID string, options container.StartOptions) error) *mockdockerAPI_ContainerStart_Call {
	_c.Call.Return(run)
	return _c
}

// ContainerStop provides a mock function for the type mockdockerAPI
func (_mock *mockdockerAPI) ContainerStop(ctx context.Context, containerID string, options container.StopOptions) error {
	ret := _mock.Called(ctx, containerID, options)

	if len(ret) == 0 {
		panic("no return value specified for ContainerStop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, container.StopOptions) error); ok {
		r0 = returnFunc(ctx, containerID, options)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockdockerAPI_ContainerStop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerStop'
type mockdockerAPI_ContainerStop_Call struct {
	*mock.Call
}

// ContainerStop is a helper method to define mock.On call
//   - ctx context.Context
//   - containerID string
//   - options container.StopOptions
func (_e *mockdockerAPI_Expecter) ContainerStop(ctx interface{}, containerID interface{}, options interface{}) *mockdockerAPI_ContainerStop_Call {
	return &mockdockerAPI_ContainerStop_Call{Call: _e.mock.On("ContainerStop", ctx, containerID, options)}
}

func (_c *mockdockerAPI_ContainerStop_Call) Run(run func(ctx context.Context, containerID string, options container.StopOptions)) *mockdockerAPI_ContainerStop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 container.StopOptions
		if args[2] != nil {
			arg2 = args[2].(container.StopOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockdockerAPI_ContainerStop_Call) Return(err error) *mockdockerAPI_ContainerStop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockdockerAPI_ContainerStop_Call) RunAndReturn(run func(ctx context.Context, containerID string, options container.StopOptions) error) *mockdockerAPI_ContainerStop_Call {
	_c.Call.Return(run)
	return _c
}

// ContainerWait provides a mock function for the type mockdockerAPI
func (_mock *mockdockerAPI) ContainerWait(ctx context.Context, containerID string, condition container.WaitCondition) (<-chan container.WaitResponse, <-chan error) {
	ret := _mock.Called(ctx, containerID, condition)

	if len(ret) == 0 {
		panic("no return value specified for ContainerWait")
	}

	var r0 <-chan container.WaitResponse
	var r1 <-chan error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, container.WaitCondition) (<-chan container.WaitResponse, <-chan error)); ok {
		return returnFunc(ctx, containerID, condition)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, container.WaitCondition) <-chan container.WaitResponse); ok {
		r0 = returnFunc(ctx, containerID, condition)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan container.WaitResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, container.WaitCondition) <-chan error); ok {
		r1 = returnFunc(ctx, containerID, condition)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(<-chan error)
		}
	}
	return r0, r1
}

// mockdockerAPI_ContainerWait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerWait'
type mockdockerAPI_ContainerWait_Call struct {
	*mock.Call
}

// ContainerWait is a helper method to define mock.On call
//   - ctx context.Context
//   - containerID string
//   - condition container.WaitCondition
func (_e *mockdockerAPI_Expecter) ContainerWait(ctx interface{}, containerID interface{}, condition interface{}) *mockdockerAPI_ContainerWait_Call {
	return &mockdockerAPI_ContainerWait_Call{Call: _e.mock.On("ContainerWait", ctx, containerID, condition)}
}

func (_c *mockdockerAPI_ContainerWait_Call) Run(run func(ctx context.Context, containerID string, condition container.WaitCondition)) *mockdockerAPI_ContainerWait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 container.WaitCondition
		if args[2] != nil {
			arg2 = args[2].(container.WaitCondition)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockdockerAPI_ContainerWait_Call) Return(waitResponseCh <-chan container.WaitResponse, errCh <-chan error) *mockdockerAPI_ContainerWait_Call {
	_c.Call.Return(waitResponseCh, errCh)
	return _c
}

func (_c *mockdockerAPI_ContainerWait_Call) RunAndReturn(run func(ctx context.Context, containerID string, condition container.WaitCondition) (<-chan container.WaitResponse, <-chan error)) *mockdockerAPI_ContainerWait_Call {
	_c.Call.Return(run)
	return _c
}

// ImageBuild provides a mock function for the type mockdockerAPI
func (_mock *mockdockerAPI) ImageBuild(ctx context.Context, buildContext io.Reader, options build.ImageBuildOptions) (build.ImageBuildResponse, error) {
	ret := _mock.Called(ctx, buildContext, options)

	if len(ret) == 0 {
		panic("no return value specified for ImageBuild")
	}

	var r0 build.ImageBuildResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.Reader, build.ImageBuildOptions) (build.ImageBuildResponse, error)); ok {
		return returnFunc(ctx, buildContext, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.Reader, build.ImageBuildOptions) build.ImageBuildResponse); ok {
		r0 = returnFunc(ctx, buildContext, options)
	} else {
		r0 = ret.Get(0).(build.ImageBuildResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, io.Reader, build.ImageBuildOptions) error); ok {
		r1 = returnFunc(ctx, buildContext, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockdockerAPI_ImageBuild_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImageBuild'
type mockdockerAPI_ImageBuild_Call struct {
	*mock.Call
}

// ImageBuild is a helper method to define mock.On call
//   - ctx context.Context
//   - buildContext io.Reader
//   - options build.ImageBuildOptions
func (_e *mockdockerAPI_Expecter) ImageBuild(ctx interface{}, buildContext interface{}, options interface{}) *mockdockerAPI_ImageBuild_Call {
	return &mockdockerAPI_ImageBuild_Call{Call: _e.mock.On("ImageBuild", ctx, buildContext, options)}
}

func (_c *mockdockerAPI_ImageBuild_Call) Run(run func(ctx context.Context, buildContext io.Reader, options build.ImageBuildOptions)) *mockdockerAPI_ImageBuild_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 io.Reader
		if args[1] != nil {
			arg1 = args[1].(io.Reader)
		}
		var arg2 build.ImageBuildOptions
		if args[2] != nil {
			arg2 = args[2].(build.ImageBuildOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockdockerAPI_ImageBuild_Call) Return(imageBuildResponse build.ImageBuildResponse, err error) *mockdockerAPI_ImageBuild_Call {
	_c.Call.Return(imageBuildResponse, err)
	return _c
}

func (_c *mockdockerAPI_ImageBuild_Call) RunAndReturn(run func(ctx context.Context, buildContext io.Reader, options build.ImageBuildOptions) (build.ImageBuildResponse, error)) *mockdockerAPI_ImageBuild_Call {
	_c.Call.Return(run)
	return _c
}

// ImagePull provides a mock function for the type mockdockerAPI
func (_mock *mockdockerAPI) ImagePull(ctx context.Context, refStr string, options image.PullOptions) (io.ReadCloser, error) {
	ret := _mock.Called(ctx, refStr, options)

	if len(ret) == 0 {
		panic("no return value specified for ImagePull")
	}

	var r0 io.ReadCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, image.PullOptions) (io.ReadCloser, error)); ok {
		return returnFunc(ctx, refStr, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, image.PullOptions) io.ReadCloser); ok {
		r0 = returnFunc(ctx, refStr, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, image.PullOptions) error); ok {
		r1 = returnFunc(ctx, refStr, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockdockerAPI_ImagePull_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImagePull'
type mockdockerAPI_ImagePull_Call struct {
	*mock.Call
}

// ImagePull is a helper method to define mock.On call
//   - ctx context.Context
//   - refStr string
//   - options image.PullOptions
func (_e *mockdockerAPI_Expecter) ImagePull(ctx interface{}, refStr interface{}, options interface{}) *mockdockerAPI_ImagePull_Call {
	return &mockdockerAPI_ImagePull_Call{Call: _e.mock.On("ImagePull", ctx, refStr, options)}
}

func (_c *mockdockerAPI_ImagePull_Call) Run(run func(ctx context.Context, refStr string, options image.PullOptions)) *mockdockerAPI_ImagePull_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 image.PullOptions
		if args[2] != nil {
			arg2 = args[2].(image.PullOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockdockerAPI_ImagePull_Call) Return(readCloser io.ReadCloser, err error) *mockdockerAPI_ImagePull_Call {
	_c.Call.Return(readCloser, err)
	return _c
}

func (_c *mockdockerAPI_ImagePull_Call) RunAndReturn(run func(ctx context.Context, refStr string, options image.PullOptions) (io.ReadCloser, error)) *mockdockerAPI_ImagePull_Call {
	_c.Call.Return(run)
	return _c
}
