// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package dynamodb

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	mock "github.com/stretchr/testify/mock"
)

// newMockddbAPI creates a new instance of mockddbAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockddbAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockddbAPI {
	mock := &mockddbAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockddbAPI is an autogenerated mock type for the ddbAPI type
type mockddbAPI struct {
	mock.Mock
}

type mockddbAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *mockddbAPI) EXPECT() *mockddbAPI_Expecter {
	return &mockddbAPI_Expecter{mock: &_m.Mock}
}

// DeleteItem provides a mock function for the type mockddbAPI
func (_mock *mockddbAPI) DeleteItem(ctx context.Context, in *dynamodb.DeleteItemInput, opts ...func(*dynamodb.Options)) (*dynamodb.DeleteItemOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteItem")
	}

	var r0 *dynamodb.DeleteItemOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.DeleteItemInput, ...func(*dynamodb.Options)) (*dynamodb.DeleteItemOutput, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.DeleteItemInput, ...func(*dynamodb.Options)) *dynamodb.DeleteItemOutput); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.DeleteItemOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodb.DeleteItemInput, ...func(*dynamodb.Options)) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockddbAPI_DeleteItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteItem'
type mockddbAPI_DeleteItem_Call struct {
	*mock.Call
}

// DeleteItem is a helper method to define mock.On call
//   - ctx context.Context
//   - in *dynamodb.DeleteItemInput
//   - opts ...func(*dynamodb.Options)
func (_e *mockddbAPI_Expecter) DeleteItem(ctx interface{}, in interface{}, opts ...interface{}) *mockddbAPI_DeleteItem_Call {
	return &mockddbAPI_DeleteItem_Call{Call: _e.mock.On("DeleteItem",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *mockddbAPI_DeleteItem_Call) Run(run func(ctx context.Context, in *dynamodb.DeleteItemInput, opts ...func(*dynamodb.Options))) *mockddbAPI_DeleteItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodb.DeleteItemInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodb.DeleteItemInput)
		}
		var arg2 []func(*dynamodb.Options)
		var variadicArgs []func(*dynamodb.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*dynamodb.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *mockddbAPI_DeleteItem_Call) Return(deleteItemOutput *dynamodb.DeleteItemOutput, err error) *mockddbAPI_DeleteItem_Call {
	_c.Call.Return(deleteItemOutput, err)
	return _c
}

func (_c *mockddbAPI_DeleteItem_Call) RunAndReturn(run func(ctx context.Context, in *dynamodb.DeleteItemInput, opts ...func(*dynamodb.Options)) (*dynamodb.DeleteItemOutput, error)) *mockddbAPI_DeleteItem_Call {
	_c.Call.Return(run)
	return _c
}

// GetItem provides a mock function for the type mockddbAPI
func (_mock *mockddbAPI) GetItem(ctx context.Context, in *dynamodb.GetItemInput, opts ...func(*dynamodb.Options)) (*dynamodb.GetItemOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetItem")
	}

	var r0 *dynamodb.GetItemOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.GetItemInput, ...func(*dynamodb.Options)) (*dynamodb.GetItemOutput, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.GetItemInput, ...func(*dynamodb.Options)) *dynamodb.GetItemOutput); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.GetItemOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodb.GetItemInput, ...func(*dynamodb.Options)) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockddbAPI_GetItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetItem'
type mockddbAPI_GetItem_Call struct {
	*mock.Call
}

// GetItem is a helper method to define mock.On call
//   - ctx context.Context
//   - in *dynamodb.GetItemInput
//   - opts ...func(*dynamodb.Options)
func (_e *mockddbAPI_Expecter) GetItem(ctx interface{}, in interface{}, opts ...interface{}) *mockddbAPI_GetItem_Call {
	return &mockddbAPI_GetItem_Call{Call: _e.mock.On("GetItem",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *mockddbAPI_GetItem_Call) Run(run func(ctx context.Context, in *dynamodb.GetItemInput, opts ...func(*dynamodb.Options))) *mockddbAPI_GetItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodb.GetItemInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodb.GetItemInput)
		}
		var arg2 []func(*dynamodb.Options)
		var variadicArgs []func(*dynamodb.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*dynamodb.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *mockddbAPI_GetItem_Call) Return(getItemOutput *dynamodb.GetItemOutput, err error) *mockddbAPI_GetItem_Call {
	_c.Call.Return(getItemOutput, err)
	return _c
}

func (_c *mockddbAPI_GetItem_Call) RunAndReturn(run func(ctx context.Context, in *dynamodb.GetItemInput, opts ...func(*dynamodb.Options)) (*dynamodb.GetItemOutput, error)) *mockddbAPI_GetItem_Call {
	_c.Call.Return(run)
	return _c
}

// PutItem provides a mock function for the type mockddbAPI
func (_mock *mockddbAPI) PutItem(ctx context.Context, in *dynamodb.PutItemInput, opts ...func(*dynamodb.Options)) (*dynamodb.PutItemOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PutItem")
	}

	var r0 *dynamodb.PutItemOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.PutItemInput, ...func(*dynamodb.Options)) (*dynamodb.PutItemOutput, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.PutItemInput, ...func(*dynamodb.Options)) *dynamodb.PutItemOutput); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.PutItemOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodb.PutItemInput, ...func(*dynamodb.Options)) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockddbAPI_PutItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutItem'
type mockddbAPI_PutItem_Call struct {
	*mock.Call
}

// PutItem is a helper method to define mock.On call
//   - ctx context.Context
//   - in *dynamodb.PutItemInput
//   - opts ...func(*dynamodb.Options)
func (_e *mockddbAPI_Expecter) PutItem(ctx interface{}, in interface{}, opts ...interface{}) *mockddbAPI_PutItem_Call {
	return &mockddbAPI_PutItem_Call{Call: _e.mock.On("PutItem",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *mockddbAPI_PutItem_Call) Run(run func(ctx context.Context, in *dynamodb.PutItemInput, opts ...func(*dynamodb.Options))) *mockddbAPI_PutItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodb.PutItemInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodb.PutItemInput)
		}
		var arg2 []func(*dynamodb.Options)
		var variadicArgs []func(*dynamodb.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*dynamodb.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *mockddbAPI_PutItem_Call) Return(putItemOutput *dynamodb.PutItemOutput, err error) *mockddbAPI_PutItem_Call {
	_c.Call.Return(putItemOutput, err)
	return _c
}

func (_c *mockddbAPI_PutItem_Call) RunAndReturn(run func(ctx context.Context, in *dynamodb.PutItemInput, opts ...func(*dynamodb.Options)) (*dynamodb.PutItemOutput, error)) *mockddbAPI_PutItem_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type mockddbAPI
func (_mock *mockddbAPI) Query(ctx context.Context, in *dynamodb.QueryInput, opts ...func(*dynamodb.Options)) (*dynamodb.QueryOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 *dynamodb.QueryOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.QueryInput, ...func(*dynamodb.Options)) (*dynamodb.QueryOutput, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.QueryInput, ...func(*dynamodb.Options)) *dynamodb.QueryOutput); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.QueryOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodb.QueryInput, ...func(*dynamodb.Options)) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockddbAPI_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type mockddbAPI_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - in *dynamodb.QueryInput
//   - opts ...func(*dynamodb.Options)
func (_e *mockddbAPI_Expecter) Query(ctx interface{}, in interface{}, opts ...interface{}) *mockddbAPI_Query_Call {
	return &mockddbAPI_Query_Call{Call: _e.mock.On("Query",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *mockddbAPI_Query_Call) Run(run func(ctx context.Context, in *dynamodb.QueryInput, opts ...func(*dynamodb.Options))) *mockddbAPI_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodb.QueryInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodb.QueryInput)
		}
		var arg2 []func(*dynamodb.Options)
		var variadicArgs []func(*dynamodb.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*dynamodb.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *mockddbAPI_Query_Call) Return(queryOutput *dynamodb.QueryOutput, err error) *mockddbAPI_Query_Call {
	_c.Call.Return(queryOutput, err)
	return _c
}

func (_c *mockddbAPI_Query_Call) RunAndReturn(run func(ctx context.Context, in *dynamodb.QueryInput, opts ...func(*dynamodb.Options)) (*dynamodb.QueryOutput, error)) *mockddbAPI_Query_Call {
	_c.Call.Return(run)
	return _c
}

// Scan provides a mock function for the type mockddbAPI
func (_mock *mockddbAPI) Scan(ctx context.Context, in *dynamodb.ScanInput, opts ...func(*dynamodb.Options)) (*dynamodb.ScanOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Scan")
	}

	var r0 *dynamodb.ScanOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.ScanInput, ...func(*dynamodb.Options)) (*dynamodb.ScanOutput, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.ScanInput, ...func(*dynamodb.Options)) *dynamodb.ScanOutput); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.ScanOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodb.ScanInput, ...func(*dynamodb.Options)) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockddbAPI_Scan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scan'
type mockddbAPI_Scan_Call struct {
	*mock.Call
}

// Scan is a helper method to define mock.On call
//   - ctx context.Context
//   - in *dynamodb.ScanInput
//   - opts ...func(*dynamodb.Options)
func (_e *mockddbAPI_Expecter) Scan(ctx interface{}, in interface{}, opts ...interface{}) *mockddbAPI_Scan_Call {
	return &mockddbAPI_Scan_Call{Call: _e.mock.On("Scan",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *mockddbAPI_Scan_Call) Run(run func(ctx context.Context, in *dynamodb.ScanInput, opts ...func(*dynamodb.Options))) *mockddbAPI_Scan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodb.ScanInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodb.ScanInput)
		}
		var arg2 []func(*dynamodb.Options)
		var variadicArgs []func(*dynamodb.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*dynamodb.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *mockddbAPI_Scan_Call) Return(scanOutput *dynamodb.ScanOutput, err error) *mockddbAPI_Scan_Call {
	_c.Call.Return(scanOutput, err)
	return _c
}

func (_c *mockddbAPI_Scan_Call) RunAndReturn(run func(ctx context.Context, in *dynamodb.ScanInput, opts ...func(*dynamodb.Options)) (*dynamodb.ScanOutput, error)) *mockddbAPI_Scan_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateItem provides a mock function for the type mockddbAPI
func (_mock *mockddbAPI) UpdateItem(ctx context.Context, in *dynamodb.UpdateItemInput, opts ...func(*dynamodb.Options)) (*dynamodb.UpdateItemOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateItem")
	}

	var r0 *dynamodb.UpdateItemOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.UpdateItemInput, ...func(*dynamodb.Options)) (*dynamodb.UpdateItemOutput, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.UpdateItemInput, ...func(*dynamodb.Options)) *dynamodb.UpdateItemOutput); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.UpdateItemOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodb.UpdateItemInput, ...func(*dynamodb.Options)) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockddbAPI_UpdateItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateItem'
type mockddbAPI_UpdateItem_Call struct {
	*mock.Call
}

// UpdateItem is a helper method to define mock.On call
//   - ctx context.Context
//   - in *dynamodb.UpdateItemInput
//   - opts ...func(*dynamodb.Options)
func (_e *mockddbAPI_Expecter) UpdateItem(ctx interface{}, in interface{}, opts ...interface{}) *mockddbAPI_UpdateItem_Call {
	return &mockddbAPI_UpdateItem_Call{Call: _e.mock.On("UpdateItem",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *mockddbAPI_UpdateItem_Call) Run(run func(ctx context.Context, in *dynamodb.UpdateItemInput, opts ...func(*dynamodb.Options))) *mockddbAPI_UpdateItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodb.UpdateItemInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodb.UpdateItemInput)
		}
		var arg2 []func(*dynamodb.Options)
		var variadicArgs []func(*dynamodb.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*dynamodb.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *mockddbAPI_UpdateItem_Call) Return(updateItemOutput *dynamodb.UpdateItemOutput, err error) *mockddbAPI_UpdateItem_Call {
	_c.Call.Return(updateItemOutput, err)
	return _c
}

func (_c *mockddbAPI_UpdateItem_Call) RunAndReturn(run func(ctx context.Context, in *dynamodb.UpdateItemInput, opts ...func(*dynamodb.Options)) (*dynamodb.UpdateItemOutput, error)) *mockddbAPI_UpdateItem_Call {
	_c.Call.Return(run)
	return _c
}
